name: Deploy MERN App with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Docker Login
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build & Push Frontend
    - name: Build Frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-frontend ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/mern-frontend

    # Build & Push Backend
    - name: Build Backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend

    # Deploy to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Stop old containers
          docker stop frontend || true
          docker stop backend || true
          docker stop mongo || true

          docker rm frontend || true
          docker rm backend || true
          docker rm mongo || true

          # Create network
          docker network create mern-net || true

          # Pull latest images
          docker pull ${{ secrets.DOCKER_USERNAME }}/mern-frontend
          docker pull ${{ secrets.DOCKER_USERNAME }}/mern-backend

          # Run MongoDB
          docker run -d --name mongo \
            --network mern-net \
            --restart always \
            mongo

          # Wait for MongoDB
          sleep 10

          # Run Backend
          docker run -d --name backend \
            --network mern-net \
            --restart always \
            -p 5000:5000 \
            ${{ secrets.DOCKER_USERNAME }}/mern-backend

          # Run Frontend
          docker run -d --name frontend \
            --restart always \
            -p 80:80 \
            ${{ secrets.DOCKER_USERNAME }}/mern-frontend
